--Paquete para poblar la base de datos--
--Se calculan variables que se derivan de otras, como la duracion de la llamada--

CREATE OR REPLACE PACKAGE PK_LLAMADA AS 
    FUNCTION CALCULAR_DURACION(INICIO DATE, FIN DATE ) RETURN NUMBER;
    FUNCTION BUSCAR_DESTINO  (TEL LLAMADA.TEL_DESTINO%TYPE) RETURN LLAMADA.NOMBRE_DESTINO%TYPE;
    FUNCTION BUSCAR_CLIENTE (TEL VARCHAR2) RETURN TELEFONO.CLIENTE_ID%TYPE;
    FUNCTION BUSCAR_PAISID (TEL LLAMADA.TEL_DESTINO%TYPE) RETURN LLAMADA.PAIS_ID%TYPE;
    FUNCTION TEL_CLIENTE ( CLI_ID TELEFONO.CLIENTE_ID%TYPE ) RETURN VARCHAR2;
END PK_LLAMADA;

CREATE OR REPLACE PACKAGE BODY PK_LLAMADA AS 

    FUNCTION CALCULAR_DURACION(INICIO DATE, FIN DATE) 
        RETURN NUMBER
    IS
        V_DURACION NUMBER:=0;
    BEGIN
        SELECT (TO_DATE(FIN) - TO_DATE(INICIO) ) INTO V_DURACION FROM DUAL; 
        RETURN V_DURACION;
    END CALCULAR_DURACION;

    FUNCTION BUSCAR_DESTINO (TEL LLAMADA.TEL_DESTINO%TYPE) 
        RETURN LLAMADA.NOMBRE_DESTINO%TYPE
    IS
        NOM_DESTINO LLAMADA.NOMBRE_DESTINO%TYPE;
    BEGIN
        SELECT  C.NOMBRE || ' ' ||  P.NOMBRE AS DESTINO INTO NOM_DESTINO  FROM PAIS P, CIUDAD C WHERE SUBSTR(TEL,1,4) = P.INDICATIVO AND SUBSTR(TEL,6,3) = C.INDICATIVO;
        RETURN NOM_DESTINO;
    END BUSCAR_DESTINO;

    FUNCTION BUSCAR_CLIENTE (TEL VARCHAR2)
        RETURN TELEFONO.CLIENTE_ID%TYPE
    IS
        CLIENTE TELEFONO.CLIENTE_ID%TYPE;
    BEGIN
        SELECT TELEFONO.CLIENTE_ID INTO CLIENTE FROM TELEFONO  WHERE  SUBSTR(TEL,6,3)= TELEFONO.INDICATIVO_CIUDAD  AND SUBSTR(TEL,10,10) = TELEFONO.NUMERO;
        RETURN CLIENTE;
    END BUSCAR_CLIENTE;

    FUNCTION BUSCAR_PAISID (TEL LLAMADA.TEL_DESTINO%TYPE) 
        RETURN LLAMADA.PAIS_ID%TYPE
    IS
        PAIS_ID_NUM LLAMADA.PAIS_ID%TYPE;
    BEGIN
        SELECT PAIS_ID INTO PAIS_ID_NUM FROM PAIS WHERE  SUBSTR(TEL ,1,4) = INDICATIVO;
        RETURN PAIS_ID_NUM;
    END BUSCAR_PAISID;

    FUNCTION TEL_CLIENTE ( CLI_ID TELEFONO.CLIENTE_ID%TYPE )
        RETURN VARCHAR2
    IS
        TEL_NUM VARCHAR2(20);
    BEGIN
        SELECT TELEFONO.INDICATIVO_PAIS||'-'||TELEFONO.INDICATIVO_CIUDAD||'-'||TELEFONO.NUMERO INTO TEL_NUM FROM TELEFONO WHERE CLI_ID = TELEFONO.CLIENTE_ID;
        RETURN TEL_NUM;
    END TEL_CLIENTE;

END PK_LLAMADA;






