
--Privilegios en usuario SYSTEM
--grant execute on utl_file to developer;
--SELECT * FROM all_tab_privs WHERE grantee = 'PUBLIC' AND table_name = 'UTL_FILE';




--CREACION DE TABLESPACES--


CREATE TABLESPACE TELEFONIA_TS DATAFILE 'TELEFONIA_TS.dbf' SIZE 1024M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TELEFONIA_TS_IDX DATAFILE 'TELEFONIA_TS_IDX.dbf' SIZE 512M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

--Creacion de usuarios y privilegios--

CREATE USER "DEVELOPER" IDENTIFIED BY "PROYECTOSB" DEFAULT TABLESPACE "TELEFONIA_TS"  TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK;
GRANT ALL PRIVILEGES TO DEVELOPER;

--Formtaro de fecha--
ALTER SESSION SET NLS_DATE_FORMAT = 'DD-MON-YYYY HH24:MI:SS';


--Tablas--

CREATE TABLE EMP_TEL_LOCAL( 
    EMP_TEL_LOCAL_NIT NUMBER(16) NOT NULL, 
    NOMBRE VARCHAR2(100), 
    CORREO VARCHAR2(50),
    VALOR_MINUTO NUMBER(8),
    CONVENIO_NO NUMBER(8) NOT NULL,
    FECHA_CONVENIO DATE DEFAULT CURRENT_DATE,
    CONSTRAINT PK_EMP_TEL_LOCAL PRIMARY KEY(EMP_TEL_LOCAL_NIT)
    );

CREATE TYPE EMP_OBJ IS OBJECT ( EMP_NIT NUMBER(16), EMP_NOMBRE VARCHAR2(100) );

CREATE TYPE EMP_TAB IS TABLE OF EMP_OBJ;


CREATE TABLE ARCHIVO(
    ARCHIVO_ID NUMBER(8) NOT NULL,
    EMP_TEL_LOCAL_NIT NUMBER(16) NOT NULL,
    ARCHIVO_RUTA VARCHAR2(250),
    FECHA_GENERACION DATE DEFAULT CURRENT_DATE,
    PERIODICIDAD VARCHAR2(50),
    CONSTRAINT PK_ARCHIVO PRIMARY KEY(ARCHIVO_ID),
    CONSTRAINT FK_ARCHIVO_EMP_TEL_LOCAL FOREIGN KEY(EMP_TEL_LOCAL_NIT) REFERENCES EMP_TEL_LOCAL(EMP_TEL_LOCAL_NIT)
    );



CREATE TABLE CLIENTE(
    CLIENTE_ID NUMBER(8) NOT NULL,
    EMP_TEL_LOCAL_NIT NUMBER(16),
    CONSTRAINT PK_CLIENTE PRIMARY KEY (CLIENTE_ID),
    CONSTRAINT FK_CLIENTE_EMP_TEL_LOCAL FOREIGN KEY(EMP_TEL_LOCAL_NIT) REFERENCES EMP_TEL_LOCAL(EMP_TEL_LOCAL_NIT)
    );


CREATE TABLE TELEFONO(
    TELEFONO_ID NUMBER(8),
    CLIENTE_ID NUMBER(8),
    INDICATIVO_PAIS VARCHAR2(7),
    INDICATIVO_CIUDAD VARCHAR2(7),
    NUMERO NUMBER (15),
    CONSTRAINT PK_TELEFONO PRIMARY KEY (TELEFONO_ID),
    CONSTRAINT FK_CLIENTE_TELEFONO FOREIGN KEY(CLIENTE_ID) REFERENCES CLIENTE(CLIENTE_ID)
    );


CREATE TABLE LLAMADA(
    LLAMADA_ID NUMBER(8) NOT NULL,
    CLIENTE_ID NUMBER(8) NOT NULL,
    ARCHIVO_ID NUMBER(8),
    TEL_ORIGEN VARCHAR2(20),
    TEL_DESTINO VARCHAR2(20),
    PAIS_ID NUMBER(8),
    NOMBRE_DESTINO VARCHAR2(100),
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE NOT NULL,
    DURACION NUMBER,
    CONSTRAINT PK_LLAMADA PRIMARY KEY (LLAMADA_ID),
    CONSTRAINT FK_LLAMADA_CLIENTE FOREIGN KEY(CLIENTE_ID) REFERENCES CLIENTE(CLIENTE_ID),
    CONSTRAINT FK_LLAMADA_ARCHIVO FOREIGN KEY(ARCHIVO_ID) REFERENCES ARCHIVO(ARCHIVO_ID)
    );
drop index clientes_idx;
create index clientes_idx
 on llamada(cliente_id);
 
 create index llamada_idx
 on llamada(llamada_id);
 
  create index fecha_idx
 on llamada(fecha_inicio);

CREATE TABLE PAIS (
    PAIS_ID NUMBER(8) NOT NULL,
    NOMBRE VARCHAR2(50),
    INDICATIVO VARCHAR2(10),
    CONSTRAINT PK_PAIS PRIMARY KEY (PAIS_ID)
    );



CREATE TABLE CIUDAD(
    CIUDAD_ID NUMBER(8) NOT NULL,
    PAIS_ID NUMBER(8) NOT NULL,
    NOMBRE VARCHAR2(50),
    INDICATIVO VARCHAR2(10),
    CONSTRAINT PK_CIUDAD PRIMARY KEY (CIUDAD_ID),
    CONSTRAINT FK_CIUDAD_PAIS FOREIGN KEY (PAIS_ID) REFERENCES PAIS(PAIS_ID)
    );


ALTER TABLE LLAMADA ADD CONSTRAINT FK_LLAMADA_PAIS FOREIGN KEY (PAIS_ID) REFERENCES PAIS(PAIS_ID);

