
INSERT INTO CIUDAD (CIUDAD_ID, PAIS_ID, NOMBRE, INDICATIVO) VALUES (SEQ_CIUDAD.NEXTVAL, 1, 'Bogota', '001' );
INSERT INTO CIUDAD (CIUDAD_ID, PAIS_ID, NOMBRE, INDICATIVO) VALUES (SEQ_CIUDAD.NEXTVAL, 1, 'Medellin','004');
INSERT INTO CIUDAD (CIUDAD_ID, PAIS_ID, NOMBRE, INDICATIVO) VALUES (SEQ_CIUDAD.NEXTVAL, 1, 'Cali', '002' );
INSERT INTO CIUDAD (CIUDAD_ID, PAIS_ID, NOMBRE, INDICATIVO) VALUES (SEQ_CIUDAD.NEXTVAL, 1, 'Barranquilla', '005' );

INSERT INTO CIUDAD (CIUDAD_ID, PAIS_ID, NOMBRE, INDICATIVO) VALUES (SEQ_CIUDAD.NEXTVAL, 2, 'Caracas', '212' );

INSERT INTO CIUDAD (CIUDAD_ID, PAIS_ID, NOMBRE, INDICATIVO) VALUES (SEQ_CIUDAD.NEXTVAL, 3, 'Miami', '305' );

INSERT INTO CIUDAD (CIUDAD_ID, PAIS_ID, NOMBRE, INDICATIVO) VALUES (SEQ_CIUDAD.NEXTVAL, 4, 'Madrid', '091' );

