
INSERT INTO EMP_TEL_LOCAL (EMP_TEL_LOCAL_NIT, NOMBRE, CORREO, VALOR_MINUTO, CONVENIO_NO) VALUES
(9000328594, 'Empresa de telefonia de Colombia', 'etc@gmail.com', 500, SEQ_CONVENIOS.NEXTVAL);
INSERT INTO EMP_TEL_LOCAL (EMP_TEL_LOCAL_NIT, NOMBRE, CORREO, VALOR_MINUTO, CONVENIO_NO) VALUES (9000329045, 'Empresa de telefonia de Medellin', 'etm@gmail.com', 470, SEQ_CONVENIOS.NEXTVAL);
INSERT INTO EMP_TEL_LOCAL (EMP_TEL_LOCAL_NIT, NOMBRE, CORREO, VALOR_MINUTO, CONVENIO_NO) VALUES (9000567996, 'Empresa de telefonia de Bogota', 'etb@gmail.com', 480, SEQ_CONVENIOS.NEXTVAL);
INSERT INTO EMP_TEL_LOCAL (EMP_TEL_LOCAL_NIT, NOMBRE, CORREO, VALOR_MINUTO, CONVENIO_NO) VALUES (9000123434, 'Empresa de telefonia de Cundinamarca', 'etcun@gmail.com', 490, SEQ_CONVENIOS.NEXTVAL);
