
INSERT INTO PAIS (PAIS_ID, NOMBRE, INDICATIVO) VALUES ( SEQ_PAIS.NEXTVAL, 'Colombia', '0057'); 
INSERT INTO PAIS (PAIS_ID, NOMBRE, INDICATIVO) VALUES ( SEQ_PAIS.NEXTVAL, 'Venezuela', '0058'); 
INSERT INTO PAIS (PAIS_ID, NOMBRE, INDICATIVO) VALUES ( SEQ_PAIS.NEXTVAL, 'USA', '0001'); 
INSERT INTO PAIS (PAIS_ID, NOMBRE, INDICATIVO) VALUES ( SEQ_PAIS.NEXTVAL, 'Espana', '0034'); 
 

